import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ace 360 - Your Career Companion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/* Header */}
            <Header/>
            <main className="min-h-screen">  {children}</main>
            {/* Footer */}
      <footer className="text-center py-8 bg-transparent text-sm">
  <div className="container mx-auto px-4 space-y-1 text-cyan-200/80">
    <p>
      © 2025 <span className="text-cyan-400 font-semibold">Ace 360</span>
    </p>
    <p>
      Crafted with care by <span className="text-cyan-400 font-semibold">Bhavya</span>.
    </p>
  </div>
</footer>


          
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
